import { Menu, Moon, Sun, Trash2 } from 'lucide-react';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { streamChat } from './api/chat'; import { fetchModels } from './api/models';
import { Composer } from './components/Composer'; import { Logo } from './components/Logo'; import { MessageItem } from './components/MessageItem'; import { Sidebar } from './components/Sidebar'; import { Welcome } from './components/Welcome';
import { DEFAULT_SYSTEM_PROMPT } from './config/assistant'; import { useTheme } from './hooks/useTheme'; import { conversationStore } from './stores/conversations';
import type { ChatMessage, Conversation, Model } from './types/chat'; import { conversationTitle, createMessage, makeId } from './utils/chat';

export default function App() {
  const [conversations, setConversations] = useState<Conversation[]>(() => conversationStore.load()); const [activeId, setActiveId] = useState<string | null>(() => conversationStore.load()[0]?.id ?? null);
  const [draft, setDraft] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [drawer, setDrawer] = useState(false); const [models, setModels] = useState<Model[]>([]); const abortRef = useRef<AbortController | null>(null); const endRef = useRef<HTMLDivElement>(null); const { theme, toggle } = useTheme();
  const active = conversations.find(c => c.id === activeId) ?? null;
  useEffect(() => conversationStore.save(conversations), [conversations]);
  useEffect(() => { const controller = new AbortController(); fetchModels(controller.signal).then(setModels).catch(() => undefined); return () => controller.abort(); }, []);
  useEffect(() => endRef.current?.scrollIntoView({ behavior: busy ? 'smooth' : 'auto' }), [active?.messages, busy]);
  const patchConversation = useCallback((id: string, patch: Partial<Conversation>) => setConversations(items => items.map(c => c.id === id ? { ...c, ...patch, updatedAt: Date.now() } : c)), []);
  const newChat = () => { abortRef.current?.abort(); setBusy(false); setActiveId(null); setDraft(''); setError(''); setDrawer(false); };

  const run = useCallback(async (text: string, baseMessages?: ChatMessage[], conversation?: Conversation | null) => {
    if (busy || !text.trim()) return; setError(''); setDraft(''); setBusy(true);
    const user = createMessage('user', text); const assistant = createMessage('assistant', ''); const current = conversation ?? active;
    const prior = baseMessages ?? current?.messages ?? []; const nextMessages = [...prior, user, assistant];
    const id = current?.id ?? makeId(); const target: Conversation = current ? { ...current, messages: nextMessages, updatedAt: Date.now() } : { id, title: conversationTitle(text), createdAt: Date.now(), updatedAt: Date.now(), messages: nextMessages, selectedModel: 'auto' };
    setActiveId(id); setConversations(items => current ? items.map(c => c.id === id ? target : c) : [target, ...items]);
    const controller = new AbortController(); abortRef.current = controller; let content = '';
    try { await streamChat({ model: target.selectedModel, messages: [{ role: 'system', content: DEFAULT_SYSTEM_PROMPT }, ...[...prior, user].map(({ role, content }) => ({ role, content }))], signal: controller.signal, onToken: token => { content += token; setConversations(items => items.map(c => c.id === id ? { ...c, messages: c.messages.map(m => m.id === assistant.id ? { ...m, content } : m), updatedAt: Date.now() } : c)); } }); }
    catch (caught) { const message = caught instanceof Error ? caught.message : 'Jatayu couldn’t reach the AI service. Please try again.'; if (!controller.signal.aborted) setError(message); }
    finally { setBusy(false); abortRef.current = null; }
  }, [active, busy]);
  const regenerate = () => { if (!active) return; const lastAssistant = active.messages.map(m => m.role).lastIndexOf('assistant'); const prior = active.messages.slice(0, lastAssistant); const lastUser = [...prior].reverse().find(m => m.role === 'user'); if (!lastUser) return; const beforeUser = prior.slice(0, prior.lastIndexOf(lastUser)); void run(lastUser.content, beforeUser, active); };
  const visibleMessages = useMemo(() => active?.messages.slice(-100) ?? [], [active?.messages]);
  return <div className="app-shell"><Sidebar open={drawer} conversations={[...conversations]} activeId={activeId} onClose={() => setDrawer(false)} onNew={newChat} onSelect={setActiveId} onRename={(id,title) => patchConversation(id,{title})} onDelete={id => { setConversations(cs => cs.filter(c => c.id !== id)); if (id === activeId) setActiveId(null); }}/><main><header><button className="icon-button menu-button" onClick={() => setDrawer(true)} aria-label="Open navigation"><Menu/></button><div className="mobile-logo"><Logo compact/></div><select aria-label="Select AI model" value={active?.selectedModel ?? 'auto'} onChange={e => active && patchConversation(active.id, { selectedModel: e.target.value })}><option value="auto">Auto · Best available</option>{models.map(m => <option key={m.id} value={m.id}>{m.name}</option>)}</select><div className="header-actions">{active && <button className="icon-button" title="Clear conversation" aria-label="Clear conversation" onClick={() => { if (confirm('Clear all messages in this conversation?')) patchConversation(active.id, { messages: [] }); }}><Trash2/></button>}<button className="icon-button" onClick={toggle} aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`}>{theme === 'dark' ? <Sun/> : <Moon/>}</button></div></header><div className="conversation" aria-live="polite">{!active || active.messages.length === 0 ? <Welcome onChoose={setDraft}/> : <div className="message-list">{active.messages.length > 100 && <p className="history-note">Showing the latest 100 messages for performance.</p>}{visibleMessages.map((message, i) => <MessageItem key={message.id} message={message} isLast={i === visibleMessages.length - 1} busy={busy} onRegenerate={regenerate} onEdit={m => { const revised = prompt('Edit your message', m.content); if (revised?.trim() && active) { const index = active.messages.findIndex(item => item.id === m.id); void run(revised, active.messages.slice(0,index), active); } }}/>) }{busy && <div className="generating"><i/><i/><i/><span>Jatayu is thinking</span></div>}<div ref={endRef}/></div>}</div>{error && <div className="error-banner" role="alert"><span>{error}</span><button onClick={regenerate}>Retry</button><button aria-label="Dismiss error" onClick={() => setError('')}>×</button></div>}<Composer value={draft} setValue={setDraft} onSend={() => void run(draft)} busy={busy} onStop={() => abortRef.current?.abort()}/></main></div>;
}
